services:
  # Mi aplicación backend
  backend:
    build: .
    container_name: mi-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=adrdb
      - PORT=8080
    depends_on:
      - db

  # Base de datos
  db:
    image: postgres:16
    container_name: adrdb
    environment:
      POSTGRES_DB: adrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
